apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: {{ .Values.ingress.rule }}
      services:
        - name: {{ .Chart.Name }}
          port: 80
